version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "${DOMAIN} -> http://webapp:8000, static.${DOMAIN}"
      STAGE: ${STAGE:-local}
    depends_on:
      - webapp
    volumes:
      - https-portal-data:/var/lib/https-portal
      - static:/var/www/vhosts/static.${DOMAIN}
    networks:
      https:

  nginx:
    image: nginx:1.23.3
    ports:
      - "8001:80"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d:ro
      - static:/var/www/static:ro
    depends_on:
      - webapp
    networks:
      https:

  webapp:
    build: .
    environment:
      DOMAIN: ${DOMAIN}
    networks:
      - https
    ports:
      - "8000:8000"
    volumes:
      - db:/db
      - static:/static

  redis:
    image: redis:7.0.11
    networks:
      - https

networks:
  https:

volumes:
  db:
  static:
  https-portal-data:
