version: "3.9"

services:
  nginx:
    image: nginx:1.23.3
    ports:
      - "8001:80"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d:ro
      - static:/var/www/static:ro
    depends_on:
      - webapp
    networks:
      https:

  webapp:
    build: .
    networks:
      - https
    ports:
      - "8000:8000"
    volumes:
      - db:/db
      - static:/static

networks:
  https:

volumes:
  db:
  static:
